### ISSUE TITLE
`file` does not exist in Python 3

### ISSUE THREAD

**Issue by chrisjbillington** [sometoby/archlinux-checkrestart#4]
I get this traceback when specifying a blacklisted file with the `-b` command line option.

```
Traceback (most recent call last):
  File "/usr/bin/checkrestart", line 738, in <module>
    main()
  File "/usr/bin/checkrestart", line 132, in main
    for line in file(f, "r"):
NameError: name 'file' is not defined
```

The fix is to use `open()` instead of `file()`

**Comment by sometoby** [comment]
I'm abandoning this repo, see #3.
